name: ambringa
favicon: null
layout_spectrum: 0.7646423978731036
typography_spectrum: 0.2035415640566498
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.444578510010615
  lightness: 0.5897055214736611
  saturation: 0.5505581577308476
  rhythmicContrast: 0.40784447453916073
purpose: []
