name: ambringa
favicon: null
layout_spectrum: 0
typography_spectrum: 0.2035415640566498
title: www.ambringa.hu
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c2d8ef'
    - '#0d111a'
    - '#9cb1cc'
    - '#2f3847'
    - '#697583'
  brandStrength: 0.444578510010615
  lightness: 0.5897055214736611
  saturation: 0.5505581577308476
  rhythmicContrast: 0.40784447453916073
purpose: []
